---
collections:
  - name: community.vmware
    version: 5.3.0
  - name: community.general
    version: 10.3.1
  - name: delinea.ss
    version: 1.1.0
  - name: redhat.openshift
    version: 4.0.1
...
